### ISSUE TITLE
Error adding plugin com.codingsans.ionic.smsRetriever.AndroidSmsRetriever

### ISSUE THREAD

**Issue by lucasteixeira2** [hanatharesh2712/ionic-native-sms-retriever-plugin-master#19]
Android Studio had the following error after running the commands: `npm run build:android` `sh gradlew.sh assembleDebug`

This is the error: 

```
V/Capacitor/Plugin: To native (Cordova plugin): callbackId: AndroidSmsRetriever1476952699, service: AndroidSmsRetriever, action: hash, actionArgs: []
W/System.err: java.lang.ClassNotFoundException: com.codingsans.ionic.smsRetriever.AndroidSmsRetriever
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at java.lang.Class.forName(Class.java:379)
        at org.apache.cordova.PluginManager.instantiatePlugin(PluginManager.java:489)
        at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:169)
        at org.apache.cordova.PluginManager.exec(PluginManager.java:122)
        at com.getcapacitor.MessageHandler.callCordovaPluginMethod(MessageHandler.java:70)
        at com.getcapacitor.MessageHandler.postMessage(MessageHandler.java:46)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:336)
        at android.os.Looper.loop(Looper.java:174)
        at android.os.HandlerThread.run(HandlerThread.java:67)
    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.codingsans.ionic.smsRetriever.AndroidSmsRetriever" on path: DexPathList[[zip file "/data/app/br.com.eudora.apprepresentante-EMy8b73sALrgAluTUJYMwA==/base.apk"],nativeLibraryDirectories=[/data/app/br.com.eudora.apprepresentante-EMy8b73sALrgAluTUJYMwA==/lib/x86, /system/lib, /system/product/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
W/System.err: 	... 12 more
I/System.out: Error adding plugin com.codingsans.ionic.smsRetriever.AndroidSmsRetriever.
E/Capacitor: Post message error:
    java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CordovaPlugin.privateInitialize(java.lang.String, org.apache.cordova.CordovaInterface, org.apache.cordova.CordovaWebView, org.apache.cordova.CordovaPreferences)' on a null object reference
        at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:171)
        at org.apache.cordova.PluginManager.exec(PluginManager.java:122)
        at com.getcapacitor.MessageHandler.callCordovaPluginMethod(MessageHandler.java:70)
        at com.getcapacitor.MessageHandler.postMessage(MessageHandler.java:46)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:336)
        at android.os.Looper.loop(Looper.java:174)
        at android.os.HandlerThread.run(HandlerThread.java:67)
V/Capacitor/Plugin: To native (Cordova plugin): callbackId: AndroidSmsRetriever1476952700, service: AndroidSmsRetriever, action: start, actionArgs: []
W/System.err: java.lang.ClassNotFoundException: com.codingsans.ionic.smsRetriever.AndroidSmsRetriever
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at java.lang.Class.forName(Class.java:379)
W/System.err:     at org.apache.cordova.PluginManager.instantiatePlugin(PluginManager.java:489)
        at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:169)
        at org.apache.cordova.PluginManager.exec(PluginManager.java:122)
        at com.getcapacitor.MessageHandler.callCordovaPluginMethod(MessageHandler.java:70)
        at com.getcapacitor.MessageHandler.postMessage(MessageHandler.java:46)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:336)
        at android.os.Looper.loop(Looper.java:174)
        at android.os.HandlerThread.run(HandlerThread.java:67)
W/System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.codingsans.ionic.smsRetriever.AndroidSmsRetriever" on path: DexPathList[[zip file "/data/app/br.com.eudora.apprepresentante-EMy8b73sALrgAluTUJYMwA==/base.apk"],nativeLibraryDirectories=[/data/app/br.com.eudora.apprepresentante-EMy8b73sALrgAluTUJYMwA==/lib/x86, /system/lib, /system/product/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
    	... 12 more
I/System.out: Error adding plugin com.codingsans.ionic.smsRetriever.AndroidSmsRetriever.
E/Capacitor: Post message error:
    java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CordovaPlugin.privateInitialize(java.lang.String, org.apache.cordova.CordovaInterface, org.apache.cordova.CordovaWebView, org.apache.cordova.CordovaPreferences)' on a null object reference
        at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:171)
        at org.apache.cordova.PluginManager.exec(PluginManager.java:122)
        at com.getcapacitor.MessageHandler.callCordovaPluginMethod(MessageHandler.java:70)
        at com.getcapacitor.MessageHandler.postMessage(MessageHandler.java:46)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:336)
        at android.os.Looper.loop(Looper.java:174)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by lucasteixeira2** [comment]
I solved this problem by adding the command: `npx cap sync` and making the build again.

**Comment by lucasteixeira2** [comment]
I have another problem. My ReactJs application is not receiving SMS. `SmsRetriever.getAppHash ()` and `SmsRetriever.startWatching ()` are running normally

**Comment by hanatharesh2712** [comment]
@lucasteixeira2 Are you sending SMS with the proper hash string which you receive from .getAppHash()?

**Comment by hanatharesh2712** [comment]
@lucasteixeira2 This image may help to resolve your issue. [https://raw.githubusercontent.com/hanatharesh2712/automatic-sms-cordova/main/hello/res/ref-images/sms%20plugin%20demo.png](https://raw.githubusercontent.com/hanatharesh2712/automatic-sms-cordova/main/hello/res/ref-images/sms%20plugin%20demo.png)
