### ISSUE TITLE
Hello, I have been testing these days the plugin with a cordova application and I am getting the same error message, I already have the latest version of the plugin where you added try catch.

### ISSUE THREAD

**Issue by ferfrasa** [hanatharesh2712/ionic-native-sms-retriever-plugin-master#34]
Hello, I have been testing these days the plugin with a cordova application and I am getting the same error message, I already have the latest version of the plugin where you added try catch.

Plugin :
Cordova vesion 10.0.0.
"cordova-android": "^9.1.0",
cordova-plugin-sms-retriever-manager 1.0.3 "Device"

I try in android studio emulator

![samgbg](https://user-images.githubusercontent.com/25188661/162085267-2533ceaa-c15c-4fe3-924e-755a9c64f69a.PNG)

java.lang.IllegalArgumentException: Receiver not registered:
 com.codingsans.ionic.smsRetriever.AndroidSmsRetriever$3@cf10c27
 at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1435)
2022-04-06 16:48:20.885 4724-4724/W/System.err:     at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1642)
2022-04-06 16:48:20.885 4724-4724/:     at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:715)
2022-04-06 16:48:20.885 4724-4724/ W/System.err:     at com.codingsans.ionic.smsRetriever.AndroidSmsRetriever.onDestroy(AndroidSmsRetriever.java:122)

I really appreciate your help

_Originally posted by @ferfrasa in https://github.com/hanatharesh2712/ionic-native-sms-retriever-plugin-master/issues/15#issuecomment-1090892810_

**Comment by hanatharesh2712** [comment]
@ferfrasa Does it crash the app or just log this message?

**Comment by ferfrasa** [comment]
The application closes at the time of opening it due to the generated exception

**Comment by ferfrasa** [comment]
> @ferfrasa Does it crash the app or just log this message?

The application closes at the time of opening it due to the generated exception

**Comment by hanatharesh2712** [comment]
@ferfrasa I have tried to reproduce the issue with Cordova 10 and the latest version of this plugin. but, I don't see any issues here.  Can you remove the android platform and add it again using the below command?
```
ionic cordova platform rm android
ionic cordova platform add android
```

**Comment by ferfrasa** [comment]
Hi @hanatharesh2712  , I deleted the platform and reinstalled the modules and I keep getting the same message, I share the screenshot of the log.

Plugin cordova-plugin-sms-retriever-manager 1.0.3 "Device"
Cordova : 10.0.0 (cordova-lib@10.1.0)
Version android  "cordova-android": "^9.1.0",

Emulador Pixel_XL_API_30_Android 11


I would appreciate your help !



![Screen Shot 2022-05-26 at 9 43 57](https://user-images.githubusercontent.com/25188661/170509983-26019cd0-931a-4cd8-8e5b-765560da130e.png)
