### ISSUE TITLE
App Crashing on Android 14 while trying to getSMS

### ISSUE THREAD

**Issue by Lornakimani62** [hanatharesh2712/ionic-native-sms-retriever-plugin-master#42]
One of RECEIVER EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
at
android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
at android.os. Parcel.createException(Parcel.java:3041) at android.os.Parcel.readException(Parcel.java:3024) at android.os.Parcel.readException(Parcel.java:2966)
at
android.app.ActivityManager$Stub$Proxy.registerReceiver
WithFeature(lActivityManager.java:6193)
at
android.app.ContextImpl.registerReceiverInternal(Contextim
pl.java:1863) at
android.app.ContextImpl.registerReceiver(ContextImpl.java:
1803) at
android.app.ContextImpl.registerReceiver(ContextImpl.java:
1791)
at
android.content.ContextWrapper.registerReceiver(ContextWr
apper.java:766)
at
com.codingsans.ionic.sms Retriever.AndroidSmsRetriever$1. onSuccess(AndroidSms Retriever.java:154)
at
com.codingsans.ionic.sms Retriever.AndroidSms Retriever$1.
onSuccess(AndroidSmsRetriever.java:145)
at com.google.android.gms.tasks.zzn.run(Unknown Source:27)
at android.os.Handler.handleCallback(Handler.java:958) at android.os.Handler.dispatchMessage(Handler.java:99) at android.os.Looper.loopOnce (Looper.java:224) at android.os.Looper.loop(Looper.java:318)
at
android.app.ActivityThread.main(ActivityThread.java:8720)
at java.lang.reflect.Method.invoke(Native Method)
at
android al
Dill -
Cancel
Send

**Comment by Richard-NC** [comment]
Hello, any update on the above issue? i am facing the same.

**Comment by hanatharesh2712** [comment]
Use the latest package available. version 1.0.5
https://www.npmjs.com/package/cordova-plugin-sms-retriever-manager/v/1.0.5?activeTab=readme
